services:
    sensor_ring:
        build:
          context: ../../
          dockerfile: ./edu_sensorring_ros1/docker/Dockerfile
        container_name: edu_sensorring_ros1-0.1.0
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 1000mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
            - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        network_mode: "host"
        command: bash -c 'cd /home/user/ros/launch_content; roslaunch edu_sensorring_ros1.launch'
        # command: /bin/bash
        # stdin_open: true
        volumes:
            - './launch_content:/home/user/ros/launch_content'
            - '~/.eduart/sensorring/:/home/user/.eduart/sensorring/'
        devices:
            - '/dev:/dev'